### ISSUE TITLE
[BUG] Center on token for circles wired behavevior

### ISSUE THREAD

**Issue by bnp800** [dmrickey/ckl-advanced-templates-pf1#15] opened 2022-06-26 07:21 UTC
**Module Version:** v1.3.0

**Describe the bug**
Setting center on token for circles will not show the target indicators on tokens, but in chat cards, and the left control panel will be frozen on templates while still able to drag tokens, to make the left control panel works, needs to click on other buttons except for token.

**To Reproduce**

1. Set the circle template to  center on token
2. Use the item
3. See error

**Expected behavior**
Properly targeting tokens, while not effecting left control panel

**Screenshots**
https://user-images.githubusercontent.com/69395973/175803870-94060540-4d02-4237-88f9-19749af34656.mp4

**Browser:**
edge

**Foundry Version:** 
v9

**Game System:** 
v80.10

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by bnp800** [comment] 2022-06-26 07:23
Also requesting compatibility with the mod [https://github.com/caewok/fvtt-walled-templates](https://github.com/caewok/fvtt-walled-templates)

**Comment by dmrickey** [comment] 2022-07-22 02:46
I'm sorry I try to check this often but I guess I've been slacking and didn't see the notification for this. For the first issue, I'll see what I can do about it. I've seen it happen a few times while I've been in the middle of rewriting things, but by the time I was done I hadn't seen it so I always chalked it up to "partially broken" code. Well I guess it's still partially broken.

For the request about walled templates, I do hope to include that at some point, but it will have to be rewritten within this mod instead of some kind of compatibility layer between the two.

**Comment by dmrickey** [comment] 2022-07-31 02:01
@bnp800 I am not able to reproduce the issue with the control panel being frozen on the template tab. Can you verify it's still an issue with pf 0.81.1? If so, then can you export the actor and upload that here and I'll try it with the exact combination you're using.

**Comment by bnp800** [comment] 2022-07-31 02:34
> 

I've tested again in pf 0.81.1, it seems frozen it's not a propper description.

The control panel will automatically switch to template tab, while it actually works as token control tab (I can drag/ select tokens, but can't place templates), and clicking token control tab will have no effect, but clicking other tabs like templates or tiles will make control panel works as usual.

**Comment by dmrickey** [comment] 2022-07-31 03:00
Oh ok. I follow now and yes that is the behavior I'm seeing now that I look more closely at it all. I'll figure out a way to resolve that.

**Comment by dmrickey** [comment] 2022-07-31 05:57
This behavior should now be fixed in 1.3.1. If you still notice issues with it after updating please reopen this issue with more details.

I've split off a new issue about Walled Template #17 . It won't be implemented any time soon, but I do have hopes that I'll get to it some day.

**Closed as completed by dmrickey** 2022-07-31 05:57 UTC
Labels: bug

**Comment by bnp800** [comment] 2022-07-31 11:34
> This behavior should now be fixed in 1.3.1. If you still notice issues with it after updating please reopen this issue with more details.
> 
> I've split off a new issue about Walled Template #17 . It won't be implemented any time soon, but I do have hopes that I'll get to it some day.

Yes, the left control panel now works fine, but the target behavior still remains:

_Setting center on token for circles will not show the target indicators on tokens, but in chat cards_

**Comment by dmrickey** [comment] 2022-07-31 14:56
Sorry, it was late when I finished up these changes and I verified that the targets were correctly shown in the chat card. I've pushed 1.3.2 and they now also select tokens in the scene as you'd expect
